version: '3.8'

services:
  pmta-monitoring-ui:
    image: pmta-monitoring-ui:latest
    container_name: pmta-monitoring-ui
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - pmta-network

networks:
  pmta-network:
    external: true 