version: '3.8'

services:
  pmta-monitoring-ui:
    build: .
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_KEY=${VITE_SUPABASE_KEY}
    networks:
      - pmta-network

networks:
  pmta-network:
    external: true 